### ISSUE TITLE
Why only 64 players per instance?

### ISSUE THREAD

**Issue by bluebear94** [networkprotocol/libyojimbo#17]
I'm genuinely curious (as some games will demand more than 64 players per area):

- what types of games are you catering to given this limit?
- how difficult is it to change this limit? For example, is it sufficient to change the value of `MaxPlayers`?
- There are obviously bandwidth considerations. I'm trying to read through the code to see what these are.

**Comment by gafferongames** [comment]
You are free to increase MaxPlayers above 64. I don't support it, because you will become more and more I/O bound and this starts moving into MMO territory, but it does work. Increasing above 1024 players also requires changes to const int MaxEncryptionMappings = 1024 and const int MaxContextMappings = 1024, which should really be some multiple of MaxPlayers. I'm going to fix this shortly, but right now they have to me manually adjusted.

To answer your other question, this library is designed primarily for first person shooter games (and other games like COOP action games).

cheers

- Glenn

**Comment by djdduty** [comment]
If you wanted more players without being too I/O bound, say you did want to create an mmo. Could you run multiple "front end" (Proxy?) servers that all clients connect to, say less than 512 clients per front end server, which just forward client information into the actual game servers and return data from the game servers to the clients? I have the feeling this is how it's done in real world scenarios.

**Comment by gafferongames** [comment]
I don't know. These aren't the sort of games I've worked on.
