### ISSUE TITLE
Latancy in the real network environment

### ISSUE THREAD

**Issue by adzhang** [networkprotocol/libyojimbo#23]
I made a echo server to test sending messages in the real network with 37ms delay. The latancy was as high as 80ms until I raised the loop frequency to 150 to reduce the latancy to 50ms. 

Packet loss? What should I do?

**Comment by gafferongames** [comment]
If you have a low packet send rate, this adds noticeable delay on top of network latency. Increasing send rate would therefore reduce this latency. This is expected behavior with any tick based network protocol (eg. packet send rate, vs. immediate process packet and reply with response type protocol).

cheers

**Comment by adzhang** [comment]
Oh, it seems that I make some mistakes artificially. I adjust the timing of processing messages which will send out immediately. It eventually consumes 64ms delay including 37ms round trip lantancy.

I have spent a long time looking for a real-time game network until I found Libyojimbo. Thanks for your contribution.
