### ISSUE TITLE
Language bindings

### ISSUE THREAD

**Issue by kkimdev** [networkprotocol/libyojimbo#24]
Hi, is there any plan to consider other language bindings in the future?  Since there are also some other languages used in game dev, I think it will be useful to have those or plan so that it's easier to create bindings(C interface?)

Personally I will be using Rust and willing to work on the binding.

**Comment by gafferongames** [comment]
Thanks. I think this is a good idea, but it's probably a bit premature because I'm still actively changing the API and have only just recently started documenting it. There will probably be a lot of changes to the API over the next few months, and it would totally suck to have to keep updating the C and Rust bindings every time I make small changes...

So I think, yes please, but maybe not quite yet?

cheers

**Comment by gafferongames** [comment]
I'm going to close this until the API stabilizes a bit more, but yes, I'm open to this in the future.

**Comment by kkimdev** [comment]
ok thanks! :)

**Comment by gafferongames** [comment]
Still not planning a C binding, I'm actually working on a pure C implementation (as GPL) over here, combining netcode, reliable and Yojimbo into one C library.

https://github.com/mas-bandwidth/snapshot
