### ISSUE TITLE
Question regarding C++ style

### ISSUE THREAD

**Issue by foonathan** [networkprotocol/libyojimbo#3]
While browsing through your code I've noticed a few odd programming choices.

For example, most of your classes have user defined destructors. Due to a very bad (and deprecated) C++ rule the compiler will implicitly generate copy ctors/assignment that do bitwise copy. If a user accidentally copies an object, they will have a double free.

Is there a special reason why you haven't disabled the copy operations?

Note that issue would have been resolved if you've used something similar to std::unique_ptr because it won't require any custom destructors.

Some of the classes are also perfect examples of C++11 move-only types. I know that game prograers have these bias against any newer C++ features but move semantics are useful.

I've also noted that you aren't using the C++ standard library but instead reimplement stuff like the min/max/randint or swap in a (partly) worse way. And you already require the C standard library and a C++ compiler, so there is the C++ library available as well.

Disclaimer: I come from /r/cpp but want to understand more of your reasons not just blindly bash you.

**Comment by gafferongames** [comment]
Thanks. Due to this library being used on embedded systems and game consoles I am intentionally avoiding the usage of C++11 and unique_ptr and modern C++ features. I appreciate that you guys might now understand why this is, but this is because most people in the game industry dislike modern C++ features. Therefore, we tend to code in the C++-lite style that you see, switching between a C-style POD approach and the occasional use of classes. That's what you see in this library.

**Comment by foonathan** [comment]
>  but this is because most people in the game industry dislike modern C++ features

I find this really sad.
While i totally agree that not every new C++ feature is good, some are helpful and can read to safer and cleaner code - if done properly.

For example, I am working on an allocator library - [memory](https://github.com/foonathan/memory). It uses C++11 features and the "modern" C++ style but still aims to be simple and easy to use.

**Comment by gafferongames** [comment]
Chin up. 10 years ago we all coded in C :)
