### ISSUE TITLE
Applicability for network audio?

### ISSUE THREAD

**Issue by mikesun** [networkprotocol/libyojimbo#32]
Curious if libyojimbo would be appropriate for carrying voice/audio streams as an alternative to something like RTP, especially if libyojimbo is already being use to carry game state updates?

**Comment by gafferongames** [comment]
It's certainly possible, and if you were implementing voice chat in a client/server game built with yojimbo - yes you would likely embed that voice data in an unreliable message.

**Comment by mikesun** [comment]
@gafferongames , in your past experience with voice chat in client/server games, have you generally implemented audio directly on top of your UDP-based game protocol as opposed to using RTP? In such a case, do you then handle jitter compensation and concealment algorithms manually?

**Comment by gafferongames** [comment]
It depends. In console titles and FPS I've seen it done usually by adding a voice section to packets, but it can also be done with a totally different server to the game. Most voice libraries do the jitter stuff for you in my experience, because it's a bit tricky. Unless you need to absolutely line it up with some in game actions, then you'd want to do it yourself. Complicated :)
