### ISSUE TITLE
Add allocateNetworkSimulator flag to NetworkTransport

### ISSUE THREAD

**Issue by Vavius** [networkprotocol/libyojimbo#34]
Currently there is no way to completely disable simulator when using NetworkTransport. 

Maybe worth adding that flag to NetworkTransport constructor, but I'm not sure about argument order - if allocateNetworkSimulator flag is the last, then I have to specify all other buffer size related args. 

More options: 
* Allocate it at runtime when SetNetworkConditions is called and delete in ClearNetworkConditions.
* Compile time switch. 

NetworkSimulator eats up significant amount of memory and drains some CPU even when network conditions at defaults.

**Comment by gafferongames** [comment]
Good point. Let me double check the code and see what the best way to do this is.

cheers

**Comment by gafferongames** [comment]
OK. I've thought about this. 

1) It's already capable to enable/disable it at runtime, so best to do this, instead of compile time #ifdef 

2) Generally try to avoid dynamic allocation at runtime in a library like this, so I don't like the SetNetworkConditions/ClearNetworkConditions option.

3) That leaves adding a flag to the ctor. My preference is at the end of the list, because if you are desiring this amount of control, I think it's OK to have to specify the other buffer size parameters as well. Also, backwards compatibility.

**Comment by gafferongames** [comment]
Fixed in c57cfa9613041f8fe9aa2153b861f92f6ef91fc4
