### ISSUE TITLE
Flow control/congestion avoidance + other questions

### ISSUE THREAD

**Issue by mikesun** [networkprotocol/libyojimbo#35]
1. Is there any kind of flow-control/congestion avoidance in libyojimbo? 

   This [post](http://gafferongames.com/networking-for-game-programmers/reliability-and-flow-control/) talks about a simple binary congestion avoidance algorithm, but it doesn't seem to be implemeneted in libyojimbo; the packet flow rate seems to be controlled by the frequency in which clients/server call `SendPackets()/WritePackets()`.

2. Until "snapshots/transport-level packet fragmentation" is implemented, it seems that the `maxPacketSize` for a Connection should be configured to be less than the MTU, yes? I'm a bit thrown off because the `DefaultMaxPacketSize = 4 * 1024;` is larger than standard MTU of 1500.

3. In the code documentation for `ReliableOrderedChannel`, it mentions:

   > Only one message block may be in flight over the network at any time, so blocks stall out message delivery slightly.

   Does single message block in flight restriction hold also for unreliable-unordered channels as well?

**Comment by gafferongames** [comment]
1. No congestion avoidance is implemented yet.

2. Yes, correct. I recommend aiming at 1200 MTU rather than 1500 though.

3. The one block message at a flight is specific to the reliable-ordered channel implementation. This does not apply to data block messages sent across the unreliable-unordered channel.

cheers
