### ISSUE TITLE
Rename serialize macros

### ISSUE THREAD

**Issue by Vavius** [networkprotocol/libyojimbo#36]
Macros from yojimbo_serialize.h look like functions in namespace, but defines ignore namespaces. I get name clash because of write_int, write_float, etc (a really common names). 

Maybe rename all of them to UPPERCASE with yojimbo prefix to match the style?

**Comment by gafferongames** [comment]
This is unfortunate, but I'd rather not have them uppercase because that would be annoying to type. If it causes problems for you, I think you can rename them locally to something that doesn't conflict.

Yes, I agree this is a bit not "perfect" but it's a stylistic thing. I spend a lot of time writing serialization functions, so I want it to be nice. Sometimes nice means, they are a little short and could conflict with other stuff. Sorry.

cheers
