### ISSUE TITLE
yojimbo_transport.cpp line 267 is suspicious

### ISSUE THREAD

**Issue by Vavius** [networkprotocol/libyojimbo#37]
BaseTransport::Reset() crashes when allocateNetworkSimulator is false.

**Comment by gafferongames** [comment]
Thanks. I'll take a look.

**Comment by gafferongames** [comment]
Yes I think this is a bug. It used to work, before the simulator could be not allocated. Previously, you always had a simulator, and if it was "allocated" that means that you owned it fully, and should discard all packets on it, otherwise it was "shared" and you should discard packets only from your address.

Fix is to just wrap this logic with if ( m_networkSimulator ).

Thanks
